name: CI

on:
    push:
        branches:
            - 'release/**'
    pull_request:

env:
    ALIAS_VERSION: '7.3'
    VERSION_FOR_ALIAS: '7.3.10'

jobs:
    ci:
        name: Build PHP ${{ matrix.php-version }} (${{ matrix.type }})

        runs-on: ubuntu-latest

        continue-on-error: true

        strategy:
            matrix:
                php-version:
                    - '7.3.10'
                    - '7.3.9'
                    - '7.3.8'
                    - '7.3.7'
                    - '7.3.6'
                    - '7.3.5'
                    - '7.3.4'
                    - '7.3.3'
                    - '7.3.2'
                    - '7.3.1'
                type: [ 'standard' ]

        steps:
            -   name: "Checkout code"
                uses: actions/checkout@v2

            -   if: matrix.type == 'alpine'
                run: ./build_alpine_version.sh ${{ matrix.php-version }}

            -   if: matrix.type == 'alpine'
                run: docker run --rm -t exozet/php-fpm:${{ matrix.php-version }}-alpine php -i

            -   if: matrix.type == 'alpine'
                run: docker run --rm -t exozet/php-fpm:${{ matrix.php-version }}-alpine php -v

            -   if: matrix.type == 'standard'
                run: ./build_version.sh ${{ matrix.php-version }}

            -   if: matrix.type == 'standard'
                run: docker run --rm -t exozet/php-fpm:${{ matrix.php-version }} php -i

            -   if: matrix.type == 'standard'
                run: docker run --rm -t exozet/php-fpm:${{ matrix.php-version }} php -v

            -   if: contains(github.ref, 'refs/head/release/')
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   if: contains(github.ref, 'refs/head/release/')
                name: Login to Quay.io
                uses: docker/login-action@v1
                with:
                    registry: quay.io
                    username: ${{ secrets.QUAY_USERNAME }}
                    password: ${{ secrets.QUAY_PASSWORD }}

            -   if: contains(github.ref, 'refs/head/release/') && matrix.php_version == env.VERSION_FOR_ALIAS
                name: "Push PHP ${{ matrix.php-version }} and for version alias ${{ env.ALIAS_VERSION }}"
                run: ./push_version.sh ${{ matrix.php-version }} ${{ env.ALIAS_VERSION }}

            -   if: contains(github.ref, 'refs/head/release/') && matrix.php_version != env.VERSION_FOR_ALIAS
                name: "Push PHP ${{ matrix.php-version }}"
                run: ./push_version.sh ${{ matrix.php-version }}
